
fields:
# product/base
- name: image
  singleValue: true
  description: URL of the main product image
- name: imageAlt
  singleValue: true
  description: Alt text of the main product image
- name: alternateImages
  singleValue: false
  description: Other product images (not in manufacturer description)
- name: metaKeywords
  singleValue: true
  description: The <meta> keywords content
- name: category
  singleValue: false
  description: The categories (e.g. from breadcrumbs)
- name: nameExtended
  singleValue: true
  description: The product name, prefixing "${brand} - " if not included in "name" and appending " - ${variantType}" if necessary (fixed per feed)
- name: listPrice
  singleValue: true
  description: The stated undiscounted price for the product
- name: price
  singleValue: true
  description: The offered price for the selected product variant - if a user clicks add to basket this is the price they would be charged
- name: availabilityText
  singleValue: true
  description: Availability as described on page for the selected variant. If there is no availability but the product can be added to cart, this field should be "In Stock"
  regExp: (.+)
  regExpReplace: In Stock
  defaultValue: Out of Stock
- name: description
  singleValue: false
  description: Product description supplied by website - may be concatenanted from multiple places; specifically not the manufacturer description
- name: descriptionBullets
  singleValue: true
  description: Number of ul > li tags in the description
  type: NUMBER
- name: brandText
  singleValue: true
  description: Product brand shown - this may actually NOT be just a brand name, e.g. "Visit the Gillette Store"
- name: manufacturer
  singleValue: true
  description: Product manufacturer
- name: quantity
  singleValue: true
  description: Quantity as described on the page
  regExp: (?:\s?([\d\.]+\s?)([bB]ar[s]?|[cC]ount|[cC]t|[fF][lL][\.]?\s?[oO][zZ][\.]?|FO|[mM][lL]|[oO][zZ][\.]?|pc|[pP]int|[pP]ops|qt|[wW]ipe[s]?).?)$|(?:\s?([\d\.]+\s?)([bB]ar[s]?|[cC]ount|[cC]|[fF][lL][\.]?\s?[oO][zZ][\.]?|FO|[mM][lL]|[oO][zZ][\.]?|pc|[pP]int|[pP]ops|qt|[wW]ipe[s]?).?\s?[\&\-\w\s]+)$
  regExpReplace: $1$2$3$4
- name: weightNet
  singleValue: true
  description: Net weight as described on the page
- name: weightGross
  singleValue: true
  description: Gross weight as described on the page
- name: gtin
  singleValue: true
  description: GTIN code (includes UPC/EAN)
- name: sku
  singleValue: true
  description: The store-specific product identifier
- name: variantId
  singleValue: true
  description: Identifier for a variant from a store where variants share the same sku
- name: mpc
  singleValue: true
  description: The manufacturer model code (unique) of the product
- name: packSize
  singleValue: true
  description: The number of packs in the product offer (if stated separately on the site to quantity)
- name: legalDisclaimer
  singleValue: true
  description: Content under "legal disclaimer" header
- name: directions
  singleValue: true
  description: Content under "directions" header
- name: warnings
  singleValue: true
  description: Content under "warnings" header
- name: ratingCount
  singleValue: true
  description: The number of ratings
  type: NUMBER
- name: aggregateRatingText
  singleValue: true
  description: The stated aggregate rating
- name: aggregateRating
  singleValue: true
  description: The stated aggregate rating normalized to be out of 5
  type: NUMBER
- name: shippingInfo
  singleValue: true
  description: Shipping information for the product
- name: shippingDimensions
  singleValue: true
  description: Stated shipping dimensions
- name: shippingWeight
  singleValue: true
  description: Stated shipping weight
- name: variantCount
  singleValue: true
  description: Number of variants listed
  type: NUMBER
- name: color
  singleValue: true
  description: A textual description of the colour
- name: colorCode
  singleValue: true
  description: A code description of the color (e.g. RGB hex)
- name: manufacturerDescription
  singleValue: false
  description: The extended description of the product supplied by the lister
- name: manufacturerImages
  singleValue: false
  description: Images within the third party description
- name: videos
  singleValue: false
  description: URLs of videos on page
- name: name
  singleValue: true
  description: The product name

#product/instore
- name: inStorePrice
  singleValue: true
  description: Price in the selected store

#product/amazon
- name: asin
  singleValue: true
  description: 
- name: coupon
  singleValue: true
  description: Text of any coupon offer
- name: amazonChoice
  singleValue: true
  description: YES or Blank
- name: amazonChoiceCategory
  singleValue: true
  description: Text of link next to Amazon choice graphic
- name: brandLink
  singleValue: true
  description: 
- name: internationalShipping
  singleValue: true
  description: Text next to bullet point
- name: salesRank
  singleValue: false
  description: Amazon best selling rank from product details (linked back) - needs to be collapsed
- name: salesRankCategory
  singleValue: false
  description: Amazon best selling rank from product details (linked back) - needs to be collapsed
- name: subscriptionPrice
  singleValue: true
  description: Subscribe and save price
- name: subscribeAndSave
  singleValue: true
  description: YES/NO
- name: heroQuickPromoHeadline
  singleValue: true
  description: See image - top section hero area
- name: heroQuickPromoImageUrl
  singleValue: true
  description: 
- name: heroQuickPromoUrl
  singleValue: true
  description: 
- name: pasin
  singleValue: true
  description: Parent asin
- name: videoLength
  singleValue: false
  description: 
- name: ingredientImagePresent
  singleValue: true
  description: 
- name: factImagePresent
  singleValue: true
  description: 
- name: largeImageCount
  singleValue: true
  description: 
  type: NUMBER
- name: variantAsins
  singleValue: true
  description: 
- name: primeFlag
  singleValue: true
  description: 
- name: lbb
  singleValue: true
  description: Check Lost by Box Requirements (just for Amazon and a couple of other stores) - LBB occurs when a product is bought from someone other than Amazon (on Amazon Website) - even though Amazon has the product "in Stock"
- name: lbbPrice
  singleValue: true
  description: 
- name: featureBullets
  singleValue: false
  description: 
- name: otherSellersName
  singleValue: false
  description: 
- name: otherSellersPrice
  singleValue: false
  description: 
- name: otherSellersShipping
  singleValue: false
  description: 
- name: secondaryImageTotal
  singleValue: true
  description: 
  type: NUMBER
- name: news
  singleValue: true
  description: 
- name: addonItem
  singleValue: true
  description: 
- name: fastTrack
  singleValue: true
  description: 

#product/food
- name: ingredientsList
  singleValue: true
  description: List of Ingredients from site - can be string of data if no discernible start/end point
- name: servingSize
  singleValue: true
  description: The size of serving Nutritional information is based on.
- name: servingSizeUom
  singleValue: true
  description: Unit of measure of serving
- name: numberOfServingsInPackage
  singleValue: true
  description: Suggested number of servings of the product.
  type: NUMBER
- name: caloriesPerServing
  singleValue: true
  description: Nutritional Information for Calories Per Serving content - Usually based on per 100g serving
- name: caloriesFromFatPerServing
  singleValue: true
  description: Nutritional Information for Calories From Fat content - Usually based on per 100g serving
  type: NUMBER
- name: totalFatPerServing
  singleValue: true
  description: Nutritional Information for Total Fat content - Usually based on per 100g serving
  type: NUMBER
- name: totalFatPerServingUom
  singleValue: true
  description: Unit of Measure Data for Total Fat content
- name: saturatedFatPerServing
  singleValue: true
  description: Nutritional Information for Saturated Fat content - Usually based on per 100g serving
  type: NUMBER
- name: saturatedFatPerServingUom
  singleValue: true
  description: Unit of Measure Data for Saturated Fat content
- name: transFatPerServing
  singleValue: true
  description: Nutritional Information for Trans Fat content - Usually based on per 100g serving
  type: NUMBER
- name: transFatPerServingUom
  singleValue: true
  description: Unit of Measure Data for Trans Fat content
- name: cholesterolPerServing
  singleValue: true
  description: Nutritional Information for Cholesterol content - Usually based on per 100g serving
  type: NUMBER
- name: cholesterolPerServingUom
  singleValue: true
  description: Unit of Measure Data for Cholesterol content
- name: sodiumPerServing
  singleValue: true
  description: Nutritional Information for Sodium content - Usually based on per 100g serving
  type: NUMBER
- name: sodiumPerServingUom
  singleValue: true
  description: Unit of Measure Data for Sodium content
- name: totalCarbPerServing
  singleValue: true
  description: Nutritional Information for Total Carbohydrate content - Usually based on per 100g serving
  type: NUMBER
- name: totalCarbPerServingUom
  singleValue: true
  description: Unit of Measure Data for Total Carbohydrate content
- name: dietaryFibrePerServing
  singleValue: true
  description: Nutritional Information for Dietary Fibre content - Usually based on per 100g serving
  type: NUMBER
- name: dietaryFibrePerServingUom
  singleValue: true
  description: Unit of Measure Data for Dietary Fibre content
- name: totalSugarsPerServing
  singleValue: true
  description: Nutritional Information for Total Sugar content - Usually based on per 100g serving
  type: NUMBER
- name: totalSugarsPerServingUom
  singleValue: true
  description: Unit of Measure Data for Total Sugar content
- name: proteinPerServing
  singleValue: true
  description: Nutritional Information for Protein content - Usually based on per 100g serving
  type: NUMBER
- name: proteinPerServingUom
  singleValue: true
  description: Unit of Measure Data for Protein
- name: vitaminAPerServing
  singleValue: true
  description: Nutritional Information for Vitamin A content - Usually based on per 100g serving
  type: NUMBER
- name: vitaminAPerServingUom
  singleValue: true
  description: Unit of Measure Data for Vitamin A
- name: vitaminCPerServing
  singleValue: true
  description: Nutritional Information for Vitamin C content - Usually based on per 100g serving
  type: NUMBER
- name: vitaminCPerServingUom
  singleValue: true
  description: Unit of Measure Data for Vitamin C
- name: calciumPerServing
  singleValue: true
  description: Nutritional Information for Calcium content - Usually based on per 100g serving
  type: NUMBER
- name: calciumPerServingUom
  singleValue: true
  description: Unit of Measure Data for Calcium
- name: ironPerServing
  singleValue: true
  description: Nutritional Information for Iron content - Usually based on per 100g serving
  type: NUMBER
- name: ironPerServingUom
  singleValue: true
  description: Unit of Measure Data for Iron
- name: dietarySymbols
  singleValue: true
  description: Information related to the dietary symbols of a specific product
- name: magnesiumPerServing
  singleValue: true
  description: Nutritional Information for Magnesium content - Usually based on per 100g serving
  type: NUMBER
- name: magnesiumPerServingUom
  singleValue: true
  description: Unit of Measure Data for Magnesium
- name: saltPerServing
  singleValue: true
  description: Nutritional Information for Salt content - Usually based on per 100g serving
  type: NUMBER
- name: saltPerServingUom
  singleValue: true
  description: Unit of Measure Data for Salt
- name: dietaryInformation
  singleValue: true
  description: 
- name: specifications
  singleValue: true
  description: The physical dimensions of the product including packaging.
- name: warranty
  singleValue: true
  description: Guarantee associated with the product
- name: storage
  singleValue: true
  description: Suggested storage location for product
- name: countryOfOrigin
  singleValue: true
  description: The country from which the product originates
- name: allergyAdvice
  singleValue: true
  description: Allergy information associated with the product
- name: recyclingInformation
  singleValue: true
  description: Recycling information associated with the product
- name: productOtherInformation
  singleValue: false
  description: Any other product information
- name: packaging
  singleValue: true
  description: Packaging information
- name: additives
  singleValue: true
  description: List of additives in the product
- name: pricePerUnit
  singleValue: true
  description: Price of the product split into certain units
- name: pricePerUnitUom
  singleValue: true
  description: The unit of measurement used in price_per_unit
- name: promotion
  singleValue: true
  description: promotion text on product page
- name: alcoholContent
  singleValue: true
  description: Alcohol content information
- name: newVersion
  singleValue: true
  description: In product page, information about a new version of the product (https://www.amazon.es/DODOT-Sensitive-Pa%C3%B1ales-Talla-240/dp/B01ELA8U0Q/ref=sr_1_4?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=dodot%2B-%2Bpa%C3%B1ales%2Bpara%2Bni&qid=1589984387&sr=8-4&th=1)
- name: newAsin
  singleValue: true
  description: In product page, information about a new version of the product - new asin info
- name: newDescription
  singleValue: true
  description: In product page, information about a new version of the product - new desription info
- name: variantInformation
  singleValue: true
  description: colour / scent / flavour / other
- name: firstVariant
  singleValue: true
  description: Unique identifier for a collection of variants. For a subset of core feeds (43) we have a column "first_variant" that is populated with a common code to link all variants for a product. method 1 (Preferred) = use common tag (Could be parent sku) that is same value for all variants of a product. method 2 = first_variant method technique, Identify the first varient in the sequence and use this rpc to populate "first_variant" for all variants of a product, this rpc becomes the common link between other variants. method 3 = apply some logic to determine link between variants, this will need analysis
- name: variants
  singleValue: false
  description: 
- name: additionalDescBulletInfo
  singleValue: false
  description: 
- name: prop65Warning
  singleValue: true
  description: 
- name: ageSuitability
  singleValue: true
  description: Recommended age displayed on the product page. https://www.amazon.com/LEGO-Classic-Medium-Creative-Brick/dp/B00NHQFA1I
  example: 4 - 99 years
- name: energyEfficiency
  singleValue: true
  description: Energy rating of a product. https://www.amazon.de/Siemens-WM16W541-Waschmaschine-Schnellwaschprogramm-Nachlegefunktion/dp/B015FJFK14
  example: A+, A+++, B
- name: technicalInformationPdfPresent
  singleValue: true
  description: If there is for example a manual in pdf format on the website. ['Yes','No']
  example: https://www.amazon.de/Hasbro-Spiele-44220100-Mastermind-Kinderspiel/dp/B0007OHUG6
  defaultValue: No
- name: termsAndConditions
  singleValue: true
  description: Terms and conditions information text ['Yes','No']
  defaultValue: No
- name: privacyPolicy
  singleValue: true
  description: Privacy Policy information text ['Yes','No']
  defaultValue: No
- name: customerServiceAvailability
  singleValue: true
  description: Information related to customer service availability (text), ['Yes','No']
  defaultValue: No
- name: materials
  singleValue: true
  description: Materials used to make the product
  example: https://www.jdsports.co.uk/product/blue-adidas-linear-20-reversible-wind-breaker-jacket/15988125/
- name: Image360Present
  singleValue: true
  description: If 360 image is present in the carousel ['Yes','No']
  example: https://www.amazon.com/Trinsic-Single-Handle-Magnetic-Champagne-9159-CZ-DST/dp/B0050EN8E6
  defaultValue: No
- name: imageZoomFeaturePresent
  singleValue: true
  description: If Zoom feature is available for Main image or images in the carousel,['Yes','No']
  example: https://www.zalando.de/adidas-neo-sneaker-low-blackwhite-a4315i002-q11.html
  defaultValue: No
  